### ISSUE TITLE
running insights-net fails bcz module not found

### ISSUE THREAD

**Issue by RHmilti** [amorenoz/insights-net#4]
i followed the README in setting up the VENV, but i cannot run the insights-net command in the VENV:

```

(venv) milti@senwosret:~/projects/github/insights-net$ pip list
Package            Version
------------------ ----------
asttokens          2.4.1
CacheControl       0.13.1
certifi            2023.11.17
charset-normalizer 3.3.2
click              8.1.7
colorama           0.4.6
comm               0.2.1
coverage           7.4.0
debugpy            1.8.0
decorator          5.1.1
defusedxml         0.7.1
executing          2.0.1
filelock           3.13.1
fixtures           4.1.0
graphviz           0.18.2
idna               3.6
insights-core      3.3.0
insights-net       0.0.2
ipykernel          6.28.0
ipython            8.20.0
jedi               0.19.1
Jinja2             3.1.2
jupyter_client     8.6.0
jupyter_core       5.7.1
lockfile           0.12.2
markdown-it-py     3.0.0
MarkupSafe         2.1.3
matplotlib-inline  0.1.6
mdurl              0.1.2
msgpack            1.0.7
nest-asyncio       1.5.8
netaddr            0.10.1
ovs                3.1.2
ovs-dbg            0.0.18
ovsdbapp           2.5.0
packaging          23.2
parso              0.8.3
pbr                6.0.0
pexpect            4.9.0
pip                23.3.2
platformdirs       4.1.0
prompt-toolkit     3.0.43
psutil             5.9.7
ptyprocess         0.7.0
pure-eval          0.2.2
Pygments           2.17.2
pyparsing          3.1.1
python-dateutil    2.8.2
PyYAML             6.0.1
pyzmq              25.1.2
redis              5.0.1
requests           2.31.0
rich               13.7.0
six                1.16.0
sortedcontainers   2.4.0
stack-data         0.6.3
tornado            6.4
traitlets          5.14.1
urllib3            2.1.0
wcwidth            0.2.13
(venv) milti@senwosret:~/projects/github/insights-net$ insights-net host -k -p insights_net.plugins /tmp/sosreports/sosreport-master-1-123-2024-01-08-nvabkgr/etc/openvswitch/conf.db 
Traceback (most recent call last):
  File "/home/milti/projects/github/insights-net/venv/bin/insights-net", line 4, in <module>
    from insights_net import commands
  File "/home/milti/projects/github/insights-net/venv/lib64/python3.12/site-packages/insights_net/commands/__init__.py", line 4, in <module>
    from .net import find_ip
  File "/home/milti/projects/github/insights-net/venv/lib64/python3.12/site-packages/insights_net/commands/net.py", line 8, in <module>
    from ovs_dbg.ofp import OFPFlow
ModuleNotFoundError: No module named 'ovs_dbg.ofp'
```
so im at a loss on who to proceed

**Comment by RHmilti** [comment]
it looks like this is a versioning issue w ovs-dbg: ovs_dbg.ofp has been renamed to ovs_dbg.parse.

ill see what restricting the versioning for this library yields.

**Comment by RHmilti** [comment]
following the README, trying to run the insights shell here, i get the following exception:

```
(venv) milti@senwosret:~/projects/github/amorenoz/insights-net$ insights shell -k -p insights_net.plugins /tmp/sosreports/sosreport-master-1-123-2024-01-08-nvabkgr/
cannot import name 'SkipException' from 'insights.parsers' (/home/milti/projects/github/amorenoz/insights-net/venv/lib64/python3.12/site-packages/insights/parsers/__init__.py)
```

**Comment by amorenoz** [comment]
Yeah, this is quite experimental and I did not keep it up to date with ovs-dbg changes.
Can you try [update_to_ovs](https://github.com/amorenoz/insights-net/tree/update_to_ovs)  branch?
